### PR TITLE
PWA cache auto updater

### PR DESCRIPTION
**Pull request by JustFrederik**
Assets will auto added to the service worker & to the dist folder. 
Every time it is compiled it will generate a version file that contains the version. The sw.js will clear the cache when the version updates
I removed the toolchain because I got an error that dependencies need at least rustc 1.67.

### CODE REVIEW

**Comment by emilk** [comment]
> I removed the toolchain because I got an error that dependencies need at least rustc 1.67.

Let's update instead: https://github.com/emilk/eframe_template/pull/106

**Comment by JustFrederik** [comment]
I didn’t know that rfd has problems with 1.72. I tried it with the stable toolchain and it worked for me so I just removed it. Il merge the updates once you added the tool chain version

**Comment by emilk** [comment]
> @emilk i can't resolve the conflict with cargo.toml since I needed to add build dependencies

I don't follow. Why can't you resolve conflicts? I sure can't do it - since you opened your PR from your `master` branch I cannot edit it.

**Comment by JustFrederik** [comment]
I meant this check:

This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
Cargo.toml
rust-toolchain

**Comment by JustFrederik** [comment]
@emilk i resolved the issue with the version

**Pull request closed without merging**
