### PR TITLE
Update eframe to v0.22

### PR DESCRIPTION
**Pull request by martinitus**
Update to eframe and egui 0.22.

- Fix compilation error caused by transition to `WebRunner` in eframe 0.22.

### CODE REVIEW

**Comment by martinitus** [comment]
Tested:
 - `cargo run`
 - `trunk serve` with `wgpu` and `glow`

**Review by martinitus — COMMENTED** [review]
I would wait for feedback and then also change the logging setup and panic hook.

**Comment by apirogov** [comment]
Thanks for this PR! I'm new to egui and Rust, maybe I'm doing something wrong, but I got issues with the logging:

* I don't get the test message "app created" in my log unless I add and init `env_logger`, but even then I don't see the message in the browser log (not sure if `env_logger` even supports this target). am I missing something or should logging 'just work'?

* I don't want to see all the `wpu` and other verbose logging stuff by default, is there a way to set the filter default level inside my app? currently I have to filter it out with `RUSTLOG=myapp=info` which apparently only lets my logs through, I don't think a super verbose gpu stuff log should be the default logging verbosity...

**Comment by emilk** [comment]
Hi - thanks for the PR, but I already updated to 0.22 in https://github.com/emilk/eframe_template/commit/5ff1713daede99d1c4fa63c9eb2d9e966a8e841a

**Pull request closed without merging**
