### PR TITLE
Provide a fill_template script

### PR DESCRIPTION
**Pull request by markusdd**
Hi.

I think this template project is a wonderful idea to play around with egui for ealuationa nd eventually starting something real with it.

But I found it kind of cumbersome to fill in the template consistently over all the files, so I wrote this little script I would like to share, in case it is deemed useful.

### CODE REVIEW

**Comment by c-git** [comment]
Thanks it is useful was about to go write one myself cuz doing the initial setup is a bit repetitive (But yours is still better than what I was going to do). Thanks.

**Comment by c-git** [comment]
I actually still ended up doing one as I wanted to customize yours a bit. Not crazy about the first iteration. I discovered [cargo-generate](https://github.com/cargo-generate/cargo-generate) and think I want to explore that option more, it seems promising and looks like it would simplify setup. (Mostly an FYI for others who also end up here)

**Review by emilk — APPROVED** [review]
Nice!

**Comment by markusdd** [comment]
my pleasure :)

I almost forgot I did this so long ago haha

**Pull request merged**
